# Generated by Django 2.2 on 2019-05-09 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL('RAW SQL CODE')
    ]
