# Generated by Django 2.2 on 2019-05-09 00:52

from django.db import migrations
from ..db_util import db_util

class Migration(migrations.Migration):
    dependencies = []
    operations = [migrations.RunSQL(statement) for statement in db_util.parse_schema()]
