# Generated by Django 2.2 on 2019-05-09 05:42

from django.db import migrations
from ..db_util import db_util

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [migrations.RunSQL(statement) for statement in db_util.parse_insertion_itemstocks()]
